[polygon]
provider  = "https://polygon-bor.publicnode.com"
explorer  = "https://polygonscan.com"
nodes     = ["https://polygon-bor.publicnode.com", "https://polygon.llamarpc.com"]
addresses = ["0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff", "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"] 
id        = 137

debug debug debug debug